/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriagemRouteImport } from './routes/triagem'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TriagemSessionIdRouteImport } from './routes/triagem.$sessionId'
import { Route as SuperAdminPlanosRouteImport } from './routes/super-admin.planos'
import { Route as SuperAdminIndicacoesRouteImport } from './routes/super-admin.indicacoes'
import { Route as SignupSucessoRouteImport } from './routes/signup.sucesso'
import { Route as SignupCanceladoRouteImport } from './routes/signup.cancelado'
import { Route as AdminUnidadesRouteImport } from './routes/admin.unidades'
import { Route as AdminTriagensRouteImport } from './routes/admin.triagens'
import { Route as AdminProfissionaisRouteImport } from './routes/admin.profissionais'
import { Route as AdminPacientesRouteImport } from './routes/admin.pacientes'
import { Route as AdminIndicacoesRouteImport } from './routes/admin.indicacoes'
import { Route as AdminEspecialidadesRouteImport } from './routes/admin.especialidades'
import { Route as AdminConhecimentoRouteImport } from './routes/admin.conhecimento'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminPacientesIdRouteImport } from './routes/admin.pacientes.$id'
import { Route as AdminProfissionaisIdHorariosRouteImport } from './routes/admin.profissionais.$id.horarios'

const TriagemRoute = TriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TriagemSessionIdRoute = TriagemSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => TriagemRoute,
} as any)
const SuperAdminPlanosRoute = SuperAdminPlanosRouteImport.update({
  id: '/super-admin/planos',
  path: '/super-admin/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndicacoesRoute = SuperAdminIndicacoesRouteImport.update({
  id: '/super-admin/indicacoes',
  path: '/super-admin/indicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSucessoRoute = SignupSucessoRouteImport.update({
  id: '/signup/sucesso',
  path: '/signup/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCanceladoRoute = SignupCanceladoRouteImport.update({
  id: '/signup/cancelado',
  path: '/signup/cancelado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnidadesRoute = AdminUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTriagensRoute = AdminTriagensRouteImport.update({
  id: '/triagens',
  path: '/triagens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfissionaisRoute = AdminProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacientesRoute = AdminPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndicacoesRoute = AdminIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEspecialidadesRoute = AdminEspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConhecimentoRoute = AdminConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacientesIdRoute = AdminPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPacientesRoute,
} as any)
const AdminProfissionaisIdHorariosRoute =
  AdminProfissionaisIdHorariosRouteImport.update({
    id: '/$id/horarios',
    path: '/$id/horarios',
    getParentRoute: () => AdminProfissionaisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/triagem': typeof TriagemRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conhecimento': typeof AdminConhecimentoRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/pacientes': typeof AdminPacientesRouteWithChildren
  '/admin/profissionais': typeof AdminProfissionaisRouteWithChildren
  '/admin/triagens': typeof AdminTriagensRoute
  '/admin/unidades': typeof AdminUnidadesRoute
  '/signup/cancelado': typeof SignupCanceladoRoute
  '/signup/sucesso': typeof SignupSucessoRoute
  '/super-admin/indicacoes': typeof SuperAdminIndicacoesRoute
  '/super-admin/planos': typeof SuperAdminPlanosRoute
  '/triagem/$sessionId': typeof TriagemSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pacientes/$id': typeof AdminPacientesIdRoute
  '/admin/profissionais/$id/horarios': typeof AdminProfissionaisIdHorariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/triagem': typeof TriagemRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conhecimento': typeof AdminConhecimentoRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/pacientes': typeof AdminPacientesRouteWithChildren
  '/admin/profissionais': typeof AdminProfissionaisRouteWithChildren
  '/admin/triagens': typeof AdminTriagensRoute
  '/admin/unidades': typeof AdminUnidadesRoute
  '/signup/cancelado': typeof SignupCanceladoRoute
  '/signup/sucesso': typeof SignupSucessoRoute
  '/super-admin/indicacoes': typeof SuperAdminIndicacoesRoute
  '/super-admin/planos': typeof SuperAdminPlanosRoute
  '/triagem/$sessionId': typeof TriagemSessionIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pacientes/$id': typeof AdminPacientesIdRoute
  '/admin/profissionais/$id/horarios': typeof AdminProfissionaisIdHorariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/triagem': typeof TriagemRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conhecimento': typeof AdminConhecimentoRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/pacientes': typeof AdminPacientesRouteWithChildren
  '/admin/profissionais': typeof AdminProfissionaisRouteWithChildren
  '/admin/triagens': typeof AdminTriagensRoute
  '/admin/unidades': typeof AdminUnidadesRoute
  '/signup/cancelado': typeof SignupCanceladoRoute
  '/signup/sucesso': typeof SignupSucessoRoute
  '/super-admin/indicacoes': typeof SuperAdminIndicacoesRoute
  '/super-admin/planos': typeof SuperAdminPlanosRoute
  '/triagem/$sessionId': typeof TriagemSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pacientes/$id': typeof AdminPacientesIdRoute
  '/admin/profissionais/$id/horarios': typeof AdminProfissionaisIdHorariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/dashboard'
    | '/login'
    | '/precos'
    | '/triagem'
    | '/admin/configuracoes'
    | '/admin/conhecimento'
    | '/admin/especialidades'
    | '/admin/indicacoes'
    | '/admin/pacientes'
    | '/admin/profissionais'
    | '/admin/triagens'
    | '/admin/unidades'
    | '/signup/cancelado'
    | '/signup/sucesso'
    | '/super-admin/indicacoes'
    | '/super-admin/planos'
    | '/triagem/$sessionId'
    | '/admin/'
    | '/admin/pacientes/$id'
    | '/admin/profissionais/$id/horarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/login'
    | '/precos'
    | '/triagem'
    | '/admin/configuracoes'
    | '/admin/conhecimento'
    | '/admin/especialidades'
    | '/admin/indicacoes'
    | '/admin/pacientes'
    | '/admin/profissionais'
    | '/admin/triagens'
    | '/admin/unidades'
    | '/signup/cancelado'
    | '/signup/sucesso'
    | '/super-admin/indicacoes'
    | '/super-admin/planos'
    | '/triagem/$sessionId'
    | '/admin'
    | '/admin/pacientes/$id'
    | '/admin/profissionais/$id/horarios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/dashboard'
    | '/login'
    | '/precos'
    | '/triagem'
    | '/admin/configuracoes'
    | '/admin/conhecimento'
    | '/admin/especialidades'
    | '/admin/indicacoes'
    | '/admin/pacientes'
    | '/admin/profissionais'
    | '/admin/triagens'
    | '/admin/unidades'
    | '/signup/cancelado'
    | '/signup/sucesso'
    | '/super-admin/indicacoes'
    | '/super-admin/planos'
    | '/triagem/$sessionId'
    | '/admin/'
    | '/admin/pacientes/$id'
    | '/admin/profissionais/$id/horarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrecosRoute: typeof PrecosRoute
  TriagemRoute: typeof TriagemRouteWithChildren
  SignupCanceladoRoute: typeof SignupCanceladoRoute
  SignupSucessoRoute: typeof SignupSucessoRoute
  SuperAdminIndicacoesRoute: typeof SuperAdminIndicacoesRoute
  SuperAdminPlanosRoute: typeof SuperAdminPlanosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triagem': {
      id: '/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof TriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/triagem/$sessionId': {
      id: '/triagem/$sessionId'
      path: '/$sessionId'
      fullPath: '/triagem/$sessionId'
      preLoaderRoute: typeof TriagemSessionIdRouteImport
      parentRoute: typeof TriagemRoute
    }
    '/super-admin/planos': {
      id: '/super-admin/planos'
      path: '/super-admin/planos'
      fullPath: '/super-admin/planos'
      preLoaderRoute: typeof SuperAdminPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/indicacoes': {
      id: '/super-admin/indicacoes'
      path: '/super-admin/indicacoes'
      fullPath: '/super-admin/indicacoes'
      preLoaderRoute: typeof SuperAdminIndicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/sucesso': {
      id: '/signup/sucesso'
      path: '/signup/sucesso'
      fullPath: '/signup/sucesso'
      preLoaderRoute: typeof SignupSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/cancelado': {
      id: '/signup/cancelado'
      path: '/signup/cancelado'
      fullPath: '/signup/cancelado'
      preLoaderRoute: typeof SignupCanceladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unidades': {
      id: '/admin/unidades'
      path: '/unidades'
      fullPath: '/admin/unidades'
      preLoaderRoute: typeof AdminUnidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/triagens': {
      id: '/admin/triagens'
      path: '/triagens'
      fullPath: '/admin/triagens'
      preLoaderRoute: typeof AdminTriagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profissionais': {
      id: '/admin/profissionais'
      path: '/profissionais'
      fullPath: '/admin/profissionais'
      preLoaderRoute: typeof AdminProfissionaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacientes': {
      id: '/admin/pacientes'
      path: '/pacientes'
      fullPath: '/admin/pacientes'
      preLoaderRoute: typeof AdminPacientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/indicacoes': {
      id: '/admin/indicacoes'
      path: '/indicacoes'
      fullPath: '/admin/indicacoes'
      preLoaderRoute: typeof AdminIndicacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/especialidades': {
      id: '/admin/especialidades'
      path: '/especialidades'
      fullPath: '/admin/especialidades'
      preLoaderRoute: typeof AdminEspecialidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conhecimento': {
      id: '/admin/conhecimento'
      path: '/conhecimento'
      fullPath: '/admin/conhecimento'
      preLoaderRoute: typeof AdminConhecimentoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacientes/$id': {
      id: '/admin/pacientes/$id'
      path: '/$id'
      fullPath: '/admin/pacientes/$id'
      preLoaderRoute: typeof AdminPacientesIdRouteImport
      parentRoute: typeof AdminPacientesRoute
    }
    '/admin/profissionais/$id/horarios': {
      id: '/admin/profissionais/$id/horarios'
      path: '/$id/horarios'
      fullPath: '/admin/profissionais/$id/horarios'
      preLoaderRoute: typeof AdminProfissionaisIdHorariosRouteImport
      parentRoute: typeof AdminProfissionaisRoute
    }
  }
}

interface AdminPacientesRouteChildren {
  AdminPacientesIdRoute: typeof AdminPacientesIdRoute
}

const AdminPacientesRouteChildren: AdminPacientesRouteChildren = {
  AdminPacientesIdRoute: AdminPacientesIdRoute,
}

const AdminPacientesRouteWithChildren = AdminPacientesRoute._addFileChildren(
  AdminPacientesRouteChildren,
)

interface AdminProfissionaisRouteChildren {
  AdminProfissionaisIdHorariosRoute: typeof AdminProfissionaisIdHorariosRoute
}

const AdminProfissionaisRouteChildren: AdminProfissionaisRouteChildren = {
  AdminProfissionaisIdHorariosRoute: AdminProfissionaisIdHorariosRoute,
}

const AdminProfissionaisRouteWithChildren =
  AdminProfissionaisRoute._addFileChildren(AdminProfissionaisRouteChildren)

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConhecimentoRoute: typeof AdminConhecimentoRoute
  AdminEspecialidadesRoute: typeof AdminEspecialidadesRoute
  AdminIndicacoesRoute: typeof AdminIndicacoesRoute
  AdminPacientesRoute: typeof AdminPacientesRouteWithChildren
  AdminProfissionaisRoute: typeof AdminProfissionaisRouteWithChildren
  AdminTriagensRoute: typeof AdminTriagensRoute
  AdminUnidadesRoute: typeof AdminUnidadesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConhecimentoRoute: AdminConhecimentoRoute,
  AdminEspecialidadesRoute: AdminEspecialidadesRoute,
  AdminIndicacoesRoute: AdminIndicacoesRoute,
  AdminPacientesRoute: AdminPacientesRouteWithChildren,
  AdminProfissionaisRoute: AdminProfissionaisRouteWithChildren,
  AdminTriagensRoute: AdminTriagensRoute,
  AdminUnidadesRoute: AdminUnidadesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TriagemRouteChildren {
  TriagemSessionIdRoute: typeof TriagemSessionIdRoute
}

const TriagemRouteChildren: TriagemRouteChildren = {
  TriagemSessionIdRoute: TriagemSessionIdRoute,
}

const TriagemRouteWithChildren =
  TriagemRoute._addFileChildren(TriagemRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrecosRoute: PrecosRoute,
  TriagemRoute: TriagemRouteWithChildren,
  SignupCanceladoRoute: SignupCanceladoRoute,
  SignupSucessoRoute: SignupSucessoRoute,
  SuperAdminIndicacoesRoute: SuperAdminIndicacoesRoute,
  SuperAdminPlanosRoute: SuperAdminPlanosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
