/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriagemRouteImport } from './routes/triagem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUnidadesRouteImport } from './routes/admin.unidades'
import { Route as AdminProfissionaisRouteImport } from './routes/admin.profissionais'
import { Route as AdminEspecialidadesRouteImport } from './routes/admin.especialidades'
import { Route as AdminProfissionaisIdHorariosRouteImport } from './routes/admin.profissionais.$id.horarios'

const TriagemRoute = TriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnidadesRoute = AdminUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfissionaisRoute = AdminProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEspecialidadesRoute = AdminEspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfissionaisIdHorariosRoute =
  AdminProfissionaisIdHorariosRouteImport.update({
    id: '/$id/horarios',
    path: '/$id/horarios',
    getParentRoute: () => AdminProfissionaisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/triagem': typeof TriagemRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/profissionais': typeof AdminProfissionaisRouteWithChildren
  '/admin/unidades': typeof AdminUnidadesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/profissionais/$id/horarios': typeof AdminProfissionaisIdHorariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/triagem': typeof TriagemRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/profissionais': typeof AdminProfissionaisRouteWithChildren
  '/admin/unidades': typeof AdminUnidadesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/profissionais/$id/horarios': typeof AdminProfissionaisIdHorariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/triagem': typeof TriagemRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/profissionais': typeof AdminProfissionaisRouteWithChildren
  '/admin/unidades': typeof AdminUnidadesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/profissionais/$id/horarios': typeof AdminProfissionaisIdHorariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/triagem'
    | '/admin/especialidades'
    | '/admin/profissionais'
    | '/admin/unidades'
    | '/admin/'
    | '/admin/profissionais/$id/horarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/triagem'
    | '/admin/especialidades'
    | '/admin/profissionais'
    | '/admin/unidades'
    | '/admin'
    | '/admin/profissionais/$id/horarios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/triagem'
    | '/admin/especialidades'
    | '/admin/profissionais'
    | '/admin/unidades'
    | '/admin/'
    | '/admin/profissionais/$id/horarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TriagemRoute: typeof TriagemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triagem': {
      id: '/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof TriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unidades': {
      id: '/admin/unidades'
      path: '/unidades'
      fullPath: '/admin/unidades'
      preLoaderRoute: typeof AdminUnidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profissionais': {
      id: '/admin/profissionais'
      path: '/profissionais'
      fullPath: '/admin/profissionais'
      preLoaderRoute: typeof AdminProfissionaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/especialidades': {
      id: '/admin/especialidades'
      path: '/especialidades'
      fullPath: '/admin/especialidades'
      preLoaderRoute: typeof AdminEspecialidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profissionais/$id/horarios': {
      id: '/admin/profissionais/$id/horarios'
      path: '/$id/horarios'
      fullPath: '/admin/profissionais/$id/horarios'
      preLoaderRoute: typeof AdminProfissionaisIdHorariosRouteImport
      parentRoute: typeof AdminProfissionaisRoute
    }
  }
}

interface AdminProfissionaisRouteChildren {
  AdminProfissionaisIdHorariosRoute: typeof AdminProfissionaisIdHorariosRoute
}

const AdminProfissionaisRouteChildren: AdminProfissionaisRouteChildren = {
  AdminProfissionaisIdHorariosRoute: AdminProfissionaisIdHorariosRoute,
}

const AdminProfissionaisRouteWithChildren =
  AdminProfissionaisRoute._addFileChildren(AdminProfissionaisRouteChildren)

interface AdminRouteChildren {
  AdminEspecialidadesRoute: typeof AdminEspecialidadesRoute
  AdminProfissionaisRoute: typeof AdminProfissionaisRouteWithChildren
  AdminUnidadesRoute: typeof AdminUnidadesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEspecialidadesRoute: AdminEspecialidadesRoute,
  AdminProfissionaisRoute: AdminProfissionaisRouteWithChildren,
  AdminUnidadesRoute: AdminUnidadesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TriagemRoute: TriagemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
